version: '3.8'

services:
  # PostgreSQL 데이터베이스 서비스
  postgres:
    image: postgres:17
    container_name: studiofragrance_db
    env_file:
      - .env.docker
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studiofragrance"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 웹 애플리케이션 서비스
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studiofragrance_app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/studiofragrance
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

# 공유 네트워크 정의
networks:
  app-network:
    driver: bridge
    name: studiofragrance_network

# 볼륨 정의
volumes:
  postgres_data:
    driver: local
    name: studiofragrance_postgres_data