services:
  server:
    container_name: company-homepage
    env_file:
      - .env
    environment:
      - DOCKER=true
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always